from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


class WSEventType(str, Enum):
    # Phase 2 events
    BILL_INSERTED = "BILL_INSERTED"
    BILL_AUTHENTICATED = "BILL_AUTHENTICATED"
    BILL_REJECTED = "BILL_REJECTED"
    COIN_INSERTED = "COIN_INSERTED"
    DISPENSE_PROGRESS = "DISPENSE_PROGRESS"
    DISPENSE_COMPLETE = "DISPENSE_COMPLETE"
    STATE_CHANGE = "STATE_CHANGE"
    ERROR = "ERROR"
    TAMPER = "TAMPER"
    DEVICE_CONNECTED = "DEVICE_CONNECTED"
    DEVICE_DISCONNECTED = "DEVICE_DISCONNECTED"

    # Phase 3 transaction events
    TRANSACTION_STARTED = "TRANSACTION_STARTED"
    TRANSACTION_STATE_CHANGED = "TRANSACTION_STATE_CHANGED"
    TRANSACTION_COMPLETE = "TRANSACTION_COMPLETE"
    TRANSACTION_CANCELLED = "TRANSACTION_CANCELLED"
    TRANSACTION_ERROR = "TRANSACTION_ERROR"

    # Phase 3 bill acceptance events
    BILL_ACCEPTING = "BILL_ACCEPTING"
    BILL_POSITIONING = "BILL_POSITIONING"
    BILL_SORTING = "BILL_SORTING"
    BILL_STORED = "BILL_STORED"

    # Phase 3 inventory events
    INVENTORY_ALERT = "INVENTORY_ALERT"
    CLAIM_TICKET = "CLAIM_TICKET"


class WSEvent(BaseModel):
    type: WSEventType
    payload: dict = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=datetime.utcnow)
